import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { motion, useMotionValue, useSpring } from "motion/react";
import { Mic, Volume2, Image as ImageIcon, Languages, Sparkles } from "lucide-react";
import React from "react";
import "./styles.css";

const EASE = [0.16, 1, 0.3, 1];

function Footer() {
  return <motion.footer className="footer" initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.5, duration: 1, ease: EASE }}><div className="footer-left"><motion.div className="subtitle" initial={{ y: 16, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.6, duration: 0.8, ease: EASE }}><i />AI-powered language intelligence</motion.div><motion.h1 initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 0.8, duration: 0.8, ease: EASE }}>Translate anything.<br />Understand everyone.</motion.h1><motion.div className="actions" initial={{ y: 16, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: 1, duration: 0.8, ease: EASE }}><a className="button primary" href="/translator">Start translating</a><a className="button secondary" href="/features">Explore features</a></motion.div></div><a className="scroll-cue" href="/#universe"><span>Explore the model</span><b>↓</b></a></motion.footer>;
}

function TopNav() {
  return <motion.header className="top-nav" initial={{ y: -16, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.8, ease: EASE }}><a className="nav-logo" href="/" aria-label="Home"><span className="logo-t">T</span></a><nav><a href="/translator">Translator</a><a href="/features">Features</a><a href="/features#how-it-works">How It Works</a><a href="/features#support">Support</a></nav></motion.header>;
}

function Details() {
  return <section className="details"><motion.section id="features" className="detail-section" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .8, ease: EASE }}><div className="detail-label">01 / CAPABILITIES</div><div className="detail-copy"><h2>Translation that<br /><em>moves with you.</em></h2><p>From a quick phrase to a live conversation, NeuralKinetics turns language into a fluid, human moment.</p></div><div className="capability-grid"><article><span>01</span><h3>Text intelligence</h3><p>Detect language automatically and translate across 150+ languages.</p></article><article><span>02</span><h3>Voice interface</h3><p>Speak naturally with voice-to-text, voice translation, and text-to-speech.</p></article><article><span>03</span><h3>Visual context</h3><p>Upload images and screenshots for fast OCR-powered translation.</p></article></div></motion.section><motion.section className="detail-section model-section" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .8, ease: EASE }}><div className="detail-label">02 / MODEL LAYER</div><div className="model-grid"><h2>Built for<br /><em>meaning.</em></h2><div className="model-list"><div><b>Context aware</b><span>Preserves tone, intent, and conversational nuance.</span></div><div><b>Multimodal by design</b><span>Understands typed language, speech, and visual text together.</span></div><div><b>Adaptive output</b><span>Returns clear translations tuned to the way people communicate.</span></div></div></div></motion.section><motion.section id="how-it-works" className="detail-section workflow" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .8, ease: EASE }}><div className="detail-label">03 / WORKFLOW</div><div className="workflow-line"><div><b>01</b><span>Speak or type</span></div><i /><div><b>02</b><span>Choose a language</span></div><i /><div><b>03</b><span>Understand instantly</span></div></div></motion.section><motion.section id="support" className="detail-section support-section" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .8, ease: EASE }}><div className="detail-label">04 / READY WHEN YOU ARE</div><h2>Language has<br /><em>no limits.</em></h2><a href="/translator" className="outline-cta">Open translator <span>↗</span></a></motion.section></section>;
}

function TranslatorPage() {
  const [text, setText] = React.useState("");
  const [result, setResult] = React.useState("");
  const [to, setTo] = React.useState("English");
  const [listening, setListening] = React.useState(false);
  const languages = ["English", "Hindi", "Spanish", "French", "German", "Japanese", "Arabic", "Chinese", "Portuguese"];
  const translate = async () => { if (!text.trim()) return; setResult("Translating…"); try { const response = await fetch("/api/translate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text, targetLanguage: to.toLowerCase(), sourceType: "text" }) }); const data = await response.json(); setResult(data.translation || data.translatedText || "Translation unavailable."); } catch { setResult("Connect the translation API to enable live translation."); } };
  const listen = () => { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) return setResult("Voice input is not supported in this browser."); const recognition = new Recognition(); recognition.lang = "en-US"; recognition.onstart = () => setListening(true); recognition.onend = () => setListening(false); recognition.onresult = (event) => setText((value) => `${value} ${event.results[0][0].transcript}`.trim()); recognition.start(); };
  return <section className="translator-page"><div className="translator-heading"><div><p className="translator-kicker"><Sparkles size={14} /> AI TRANSLATOR</p><h1>Every language.<br />One conversation.</h1></div><p>Translate text, speech, and images<br />in one intelligent workspace.</p></div><div className="translator-card"><div className="language-bar"><span><Languages size={15} /> Language pair</span><select defaultValue="Auto detect"><option>Auto detect</option>{languages.map((language) => <option key={language}>{language}</option>)}</select><b>→</b><select value={to} onChange={(event) => setTo(event.target.value)}>{languages.map((language) => <option key={language}>{language}</option>)}</select></div><div className="translation-grid"><div className="translation-panel"><small>Auto detect</small><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Type, paste, or speak something…" /><div className="panel-actions"><button onClick={listen} className={listening ? "active" : ""}><Mic size={15} /> {listening ? "Listening" : "Voice input"}</button><label><ImageIcon size={15} /> Image OCR<input type="file" accept="image/*" hidden /></label></div></div><div className="translation-panel"><small>{to}</small><div className="translation-result">{result || "Your translation will appear here."}</div><div className="panel-actions"><button onClick={() => result && window.speechSynthesis?.speak(new SpeechSynthesisUtterance(result))}><Volume2 size={15} /> Listen</button></div></div></div><button className="translate-action" onClick={translate}>Translate <span>↗</span></button></div><div className="translator-features"><span><Mic size={16} /> Voice-to-text</span><span><Volume2 size={16} /> Text-to-speech</span><span><ImageIcon size={16} /> OCR ready</span><span><Languages size={16} /> 150+ languages</span></div></section>;
}

const storyFormats = ["Text", "PDF", "Word", "PowerPoint", "Excel", "Images", "Camera", "Voice", "Audio", "Videos", "Scanned Documents", "Handwriting", "Websites", "Emails", "Books", "Subtitles", "Notes"];
const storyLanguages = ["Hello", "Bonjour", "Hola", "नमस्ते", "こんにちは", "안녕하세요", "مرحبا", "Привет", "Ciao", "Olá", "你好", "สวัสดี", "Salam", "Shalom", "Merhaba", "Jambo"];

function StorySections() {
  const [demoText, setDemoText] = React.useState("");
  return <section className="story"><motion.section id="universe" className="story-block universe" initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }}><div className="word-cloud">{storyLanguages.map((word, index) => { const lane = Math.floor(index / 2); const left = index % 2 === 0 ? 4 + (lane % 3) * 7 : 76 - (lane % 3) * 5; return <span key={word} style={{ "--i": index, left: `${left}%`, top: `${8 + lane * 6}%` }}>{word}</span>; })}</div><div className="story-center"><small>01 / AI LANGUAGE UNIVERSE</small><h2>Every language deserves to be understood.</h2><p>Powered by advanced AI capable of understanding context, meaning, tone, and intent.</p></div></motion.section><motion.section className="story-block why" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }}><small>02 / WHY WE BUILT THIS</small><h2>Translation should<br /><em>never be a barrier.</em></h2><p>Most translators replace words. Our AI understands what people mean, wherever language takes them.</p><span className="meaning-anchor" aria-label="Hover to translate Japanese greeting" /><div className="scenario-row"><span>Research</span><span>Travel</span><span>Business</span><span>Medical</span><span>Legal</span><span>Code</span></div></motion.section><motion.section className="story-block formats" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }}><small>04 / EVERYTHING YOU CAN TRANSLATE</small><h2>One intelligence.<br /><em>Every format.</em></h2><div className="format-grid">{storyFormats.map((format) => <span key={format}>{format}</span>)}</div></motion.section><motion.section className="story-block demo" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }}><small>05 / LIVE AI DEMO</small><h2>Try the<br /><em>understanding layer.</em></h2><div className="demo-card"><textarea value={demoText} onChange={(event) => setDemoText(event.target.value)} placeholder="Type something to translate…" /><div className="demo-output">{demoText ? `Understanding: ${demoText}` : "Your translation will appear here…"}<small>Auto detect · 98% confidence · 4 sec read</small></div></div></motion.section><motion.section className="story-block voice" initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }}><small>06 / AI VOICE INTELLIGENCE</small><h2>Let your voice<br /><em>travel further.</em></h2><div className="waveform">{Array.from({ length: 28 }, (_, index) => <i key={index} style={{ "--wave": (index * 17) % 30 + 10 }} />)}</div><p>Speech recognition · Real-time translation · Accent detection · Natural pronunciation</p></motion.section></section>;
}

function App() {
  const isTranslator = window.location.pathname === "/translator";
  const isFeatures = window.location.pathname === "/features";
  const cursorX = useSpring(useMotionValue(0), { stiffness: 90, damping: 18 });
  const cursorY = useSpring(useMotionValue(0), { stiffness: 90, damping: 18 });
  const cursorRotateY = useSpring(useMotionValue(0), { stiffness: 80, damping: 16 });
  const cursorRotateX = useSpring(useMotionValue(0), { stiffness: 80, damping: 16 });
  const handlePointerMove = (event) => { if (isTranslator || isFeatures) return; const x = (event.clientX / window.innerWidth - .5) * 2; const y = (event.clientY / window.innerHeight - .5) * 2; cursorX.set(x * 48); cursorY.set(y * 30); cursorRotateY.set(x * 7); cursorRotateX.set(y * -5); };
  const resetPointer = () => { cursorX.set(0); cursorY.set(0); cursorRotateX.set(0); cursorRotateY.set(0); };
  return <main id="top" onPointerMove={handlePointerMove} onPointerLeave={resetPointer} className={`page ${isTranslator || isFeatures ? "inner-route" : ""}`}>{!isTranslator && !isFeatures && <><motion.div className="video-wrap" style={{ x: cursorX, y: cursorY, rotateX: cursorRotateX, rotateY: cursorRotateY }} initial={{ opacity: 0, scale: 1.05 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.65, ease: EASE }}><video autoPlay muted playsInline preload="auto" src="/robotic-hand.mp4" /></motion.div><Footer /><StorySections /></>}{isTranslator && <TranslatorPage />}{isFeatures && <Details />}<TopNav /></main>;
}

createRoot(document.getElementById("root")).render(<StrictMode><App /></StrictMode>);
